{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 52, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[http://example.com-http://example.com/]", "rerun": "0"}, "1": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[https://www.example.co.uk/path?a=1-https://www.example.co.uk/path?a=1]", "rerun": "0"}, "2": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[http://EXAMPLE.com:80/./path/../other/-http://example.com/other/]", "rerun": "0"}, "3": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[https://xn--mnchen-3ya.de/path-https://xn--mnchen-3ya.de/path]", "rerun": "0"}, "4": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[https://example.com/path/-https://example.com/path/]", "rerun": "0"}, "5": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_valid_url_initialization[https://example.com/path-https://example.com/path]", "rerun": "0"}, "6": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[javascript:alert(1)-Disallowed scheme]", "rerun": "0"}, "7": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[file:///path/to/file.txt-Disallowed scheme]", "rerun": "0"}, "8": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[ftp://user:pass@example.com-Disallowed scheme: ftp]", "rerun": "0"}, "9": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://<invalid>.com-Invalid label chars in: <invalid>]", "rerun": "0"}, "10": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://example.com:99999-ValueError: Port out of range 0-65535]", "rerun": "0"}, "11": {"status": "FAIL", "message": "   assert True is False\n    +  where True = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f13709742e0>.is_valid\n", "test_name": "test_invalid_url_initialization[http://example.com/../../etc/passwd-Directory traversal attempt detected in path]", "rerun": "0"}, "12": {"status": "FAIL", "message": "   AssertionError: Expected error containing 'Invalid chars in decoded query' but got 'Invalid chars in query' for URL 'http://example.com/?q=<script>'\n   assert 'Invalid chars in decoded query' in 'Invalid chars in query'\n    +  where 'Invalid chars in query' = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370a32b20>.error_message\n", "test_name": "test_invalid_url_initialization[http://example.com/?q=<script>-Invalid chars in decoded query]", "rerun": "0"}, "13": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://192.168.1.1-Private IP not allowed: 192.168.1.1]", "rerun": "0"}, "14": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://127.0.0.1-Private IP not allowed: 127.0.0.1]", "rerun": "0"}, "15": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[-URL cannot be None or empty]", "rerun": "0"}, "16": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[None-URL cannot be None or empty]", "rerun": "0"}, "17": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://example.com/path%00.txt-Null byte detected in raw URL path or query]", "rerun": "0"}, "18": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://example..com-Invalid domain label length or empty label]", "rerun": "0"}, "19": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://-example.com-Invalid label chars in: -example]", "rerun": "0"}, "20": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://example-.com-Invalid label chars in: example-]", "rerun": "0"}, "21": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://example.c-Invalid TLD length]", "rerun": "0"}, "22": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_invalid_url_initialization[http://localhost:8080-Disallowed host: localhost]", "rerun": "0"}, "23": {"status": "FAIL", "message": "   AssertionError: Expected error containing 'Private IP not allowed: ::1' but got 'Missing host' for URL 'http://[::1]/test'\n   assert 'Private IP not allowed: ::1' in 'Missing host'\n    +  where 'Missing host' = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370a338b0>.error_message\n", "test_name": "test_invalid_url_initialization[http://[::1]/test-Private IP not allowed: ::1]", "rerun": "0"}, "24": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[page2.html-http://example.com/docs/page1.html-http://example.com/docs/page2.html]", "rerun": "0"}, "25": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[../index.html-http://example.com/docs/page1.html-http://example.com/index.html]", "rerun": "0"}, "26": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[/images/logo.png-http://example.com/docs/page1.html-http://example.com/images/logo.png]", "rerun": "0"}, "27": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[//other.com/path-https://example.com/docs/-https://other.com/path]", "rerun": "0"}, "28": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[?query=new-http://example.com/page?a=1-http://example.com/page?query=new]", "rerun": "0"}, "29": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[#fragment-http://example.com/page-http://example.com/page]", "rerun": "0"}, "30": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[path/./../sub/./file-http://example.com/base/-http://example.com/base/sub/file]", "rerun": "0"}, "31": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_relative_url_resolution[path/-http://example.com/base-http://example.com/path/]", "rerun": "0"}, "32": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'scheme' property.\n", "test_name": "test_url_properties", "rerun": "0"}, "33": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[https://www.example.co.uk/path-www-example-co.uk-example.co.uk]", "rerun": "0"}, "34": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[http://blog.example.com-blog-example-com-example.com]", "rerun": "0"}, "35": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[https://justadomain.com-None-justadomain-com-justadomain.com]", "rerun": "0"}, "36": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[http://xn--mnchen-3ya.de-None-xn--mnchen-3ya-de-xn--mnchen-3ya.de]", "rerun": "0"}, "37": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[http://localhost:8080-None-localhost-None-localhost]", "rerun": "0"}, "38": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[http://[::1]-None-::1-None-::1]", "rerun": "0"}, "39": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'subdomain' property.\n", "test_name": "test_tldextract_properties[http://10.0.0.1-None-10.0.0.1-None-10.0.0.1]", "rerun": "0"}, "40": {"status": "PASS", "message": "", "test_name": "test_tldextract_fallback", "rerun": "0"}, "41": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f13711b49e0>.url_type\n", "test_name": "test_url_type_determination[https://example.com/path-https://example.com/base-URLType.INTERNAL]", "rerun": "0"}, "42": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370977220>.url_type\n", "test_name": "test_url_type_determination[/relative/path-https://example.com/base-URLType.INTERNAL]", "rerun": "0"}, "43": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370a32500>.url_type\n", "test_name": "test_url_type_determination[https://www.example.com/path-https://example.com/base-URLType.INTERNAL]", "rerun": "0"}, "44": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.EXTERNAL: 2>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f13709771b0>.url_type\n", "test_name": "test_url_type_determination[http://example.com/path-https://example.com/base-URLType.EXTERNAL]", "rerun": "0"}, "45": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.EXTERNAL: 2>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f13711a0740>.url_type\n", "test_name": "test_url_type_determination[https://other.com/path-https://example.com/base-URLType.EXTERNAL]", "rerun": "0"}, "46": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f13711a2030>.url_type\n", "test_name": "test_url_type_determination[page.html-https://example.com/base/-URLType.INTERNAL]", "rerun": "0"}, "47": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370a0ea40>.url_type\n", "test_name": "test_url_type_determination[https://example.com:443/path-https://example.com/base-URLType.INTERNAL]", "rerun": "0"}, "48": {"status": "FAIL", "message": "   assert <URLType.UNKNOWN: 3> == <URLType.INTERNAL: 1>\n    +  where <URLType.UNKNOWN: 3> = <[TypeError(\"No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\") raised in repr()] URLInfo object at 0x7f1370a0e110>.url_type\n", "test_name": "test_url_type_determination[https://example.com:8443/path-https://example.com/base-URLType.INTERNAL]", "rerun": "0"}, "49": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_url_equality_and_hash", "rerun": "0"}, "50": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'query_params' property.\n", "test_name": "test_immutability", "rerun": "0"}, "51": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_fragment_removal", "rerun": "0"}, "52": {"status": "FAIL", "message": "       TypeError: No '__dict__' attribute on 'URLInfo' instance to cache 'normalized_url' property.\n", "test_name": "test_long_url_edge_case", "rerun": "0"}, "53": {"status": "PASS", "message": "", "test_name": "test_url_info_performance", "rerun": "0"}}, "suite_name": "tests/url/test_info.py"}}}, "date": "May 01, 2025", "start_time": 1746088270.9568772, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "52", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "54"}